services:
    backend: 
        container_name: backend
        build: .
        ports: 
          - 3030:3030
        restart: always
        environment:
          DB_IP: "192.168.1.36"
          DB_PORT: "27017"
          DB_BASENAME: "nidestertestingDB"
          PORT: 3030